# Generated by Django 4.2 on 2023-09-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_dane'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zapis',
            new_name='ZapisNewsletter',
        ),
        migrations.DeleteModel(
            name='Dane',
        ),
    ]
