# Generated by Django 4.2 on 2023-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_rename_zapis_zapisnewsletter_delete_dane'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZapisVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
